Add missing type casting
Fixes 8 similar errors in Visual Studio 2015:
Error C2440 '=': cannot convert from 'const char (*)[100]' to 'char **'
Error C2664 'int snprintf(char *const ,const size_t,const char *const
,...)': cannot convert argument 1 from 'const char [100]' to 'char
*const '