Issue #435: Fix botan build without EDDSA
Loading libsofthsm2.so (built on Ubuntu 14.04 with botan) failed with:

    ERROR: Could not load the PKCS#11 library/module: src/lib/libsofthsm2.so: undefined symbol: _ZN17BotanEDPrivateKeyD1Ev

Fixes #435 (a regression in 2.5.0 due to commit 2751555).